require("aarongreenlee.plugins-setup")
require("aarongreenlee.core.options")
require("aarongreenlee.core.keymaps")
require("aarongreenlee.core.colorscheme")
require("aarongreenlee.plugins.comment")
require("aarongreenlee.plugins.nvim-tree")
require("aarongreenlee.plugins.lualine")
